service: grouplite
app: grouplite-app
org: alexjonjarvis

provider:
  name: aws
  runtime: python3.8
  role: arn:aws:iam::986870807352:role/lambda-vpc-role

  vpc:
    securityGroupIds:
      - sg-19f02336
    subnetIds:
      - subnet-1b556a25
      - subnet-20fb406d
      - subnet-37278539
      - subnet-904cb9cf
      - subnet-beab5d9f
      - subnet-cddd35ab

  environment:
    RDS_HOST: 'grouplite-db.clidohi5pcdd.us-east-1.rds.amazonaws.com'
    DB_PASS: 'SolidSnake21!'
    DB_USERNAME: 'alexj'
    DB_NAME: 'grouplitedb'
    TOKEN_SECRET: '0603'

plugins:
  - serverless-offline

package:
  individually: true
  exclude:
    - venv/**

functions:
  auth:
    handler: authentication/sessions.auth

  get_users:
    handler: users/users.get_users
    events:
      - http:
          method: GET
          path: /user
          cors: true
          authorizer: auth

  create_group:
    handler: group/group.create_group
    events:
      - http:
          method: POST
          path: /group
          cors: true
          authorizer: auth

  get_group:
    handler: group/group.get_group
    events:
      - http:
          method: GET
          path: /group
          cors: true
          authorizer: auth

  get_group_members:
    handler: group/membership.get_group_members
    events:
      - http:
          method: GET
          path: /group/members
          cors: true
          authorizer: auth

  get_user_groups:
    handler: group/membership.get_user_groups
    events:
      - http:
          method: GET
          path: /user/groups
          cors: true
          authorizer: auth

  add_membership:
    handler: group/membership.add_membership
    events:
      - http:
          method: POST
          path: /group/members
          cors: true
          authorizer: auth

  create_post:
    handler: group/posts.create_post
    events:
      - http:
          method: POST
          path: /group/posts
          cors: true
          authorizer: auth

  get_users_posts:
    handler: group/posts.get_users_posts
    events:
      - http:
          method: GET
          path: /user/posts
          cors: true
          authorizer: auth

  get_group_posts:
    handler: group/posts.get_group_posts
    events:
      - http:
          method: GET
          path: /group/posts
          cors: true
          authorizer: auth

  get_post:
    handler: group/posts.get_post
    events:
      - http:
          method: GET
          path: /posts
          cors: true
          authorizer: auth

  signup:
    handler: users/users.post_user
    events:
      - http:
          method: POST
          path: /user
          cors: true

  login:
    handler: authentication/sessions.login
    events:
      - http:
          method: POST
          path: /login
          cors: true